<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPublicMethodParameterRector;
use Rector\DeadCode\Rector\If_\RemoveAlwaysTrueIfConditionRector;

// phpcs:disable SlevomatCodingStandard.Arrays.DisallowPartiallyKeyed.DisallowedPartiallyKeyed
return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/config',
        __DIR__ . '/public',
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withPhpSets()
    ->withRootFiles()
    ->withSkip([
        // Ignores autogenerated files in tests
        'tests/Support/_generated',
        // It removes conditions based on constants with predefined values
        RemoveAlwaysTrueIfConditionRector::class,
        // Skips example test files
        RemoveUnusedPublicMethodParameterRector::class => __DIR__ . '/tests/Functional/ExampleCest.php',
    ])
    ->withAttributesSets(symfony: true, doctrine: true, phpunit: true)
    ->withComposerBased(
        twig: true,
        doctrine: true,
        symfony: true,
    )
    ->withTypeCoverageLevel(63)
    ->withDeadCodeLevel(59)
    ->withCodeQualityLevel(78);
